### ISSUE TITLE
Process-SetupDiag.ps1 tries to delete C:\Windows\System32 folder

### ISSUE THREAD

**Issue by bachirica** [AdamGrossTX/Windows10FeatureUpdates#29]
Hi Adam!!

We've recently experienced an issue with one of our customers where Process-SetupDiag.ps1 has deleted critical system files from the system32 folder forcing us to redeploy hundreds of machines. We know it was caused by that script and we're trying to understand the reason.

As I see it, Process-SetupDiag.ps1 expects certain parameters as an input, being LocalLogRoot one of them

`param (        [string]$LocalLogRoot,`

At the beginning of the script, all the contents from that $LocalLogRoot are deleted recursively

```
#cleanup any existing logs
Get-ChildItem -Path $TranscriptPath,$LocalLogRoot -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue | Out-Null
```
All good for now... but the remediation script of the "Feature Update - SetupDiag Results" configuration item seems to call the scripts without any parameter

```
#SetupDiag Remediation
[cmdletbinding()]
Param(
    $IncomingValue,
    [string]$ScriptPath = "C:\~FeatureUpdateTemp\Scripts\Process-SetupDiag.ps1"
)
. $ScriptPath
Process-SetupDiag
```
And I think that by providing no value for that parameter, as it's being executed with the SYSTEM credential, it has defaulted to C:\Windows\System32 and tried to delete all the contents

**Comment by AdamGrossTX** [comment]
The path to the logs is set during the installation of the framework using SetupFUFramework.ps1. Line 65 has the following line

https://github.com/AdamGrossTX/Windows10FeatureUpdates/blob/c261039db3a50d2e85ee345a77c973b8561b37a9/SetupFUFramework.ps1#L65

`    [string]$FUTempPath = "C:\~FeatureUpdateTemp",`


Process-SetupDiag.ps1 located here https://github.com/AdamGrossTX/Windows10FeatureUpdates/blob/master/Templates/Process-SetupDiag.ps1 is a template script.  

During the framework install, this file is modified to update the script param `$LocalLogRoot` to be the path set for $FUTempPath\Logs.  

https://github.com/AdamGrossTX/Windows10FeatureUpdates/blob/c261039db3a50d2e85ee345a77c973b8561b37a9/SetupFUFramework.ps1#L252

`        $NewProcessSetupDiagContent = $ProcessSetupDiagContent.Replace('[string]$LocalLogRoot',"[string]`$LocalLogRoot = `"$($FUTempPath)\Logs`"").Replace('[string]$TranscriptPath',"[string]`$TranscriptPath = `"$($LogPath)\$($LogPrefix)-$($ProcessSetupDiagScriptPath.BaseName).log`"")`


If your Process-SetupDiag script doesn't have a path hardcoded for that param, then something was misconfigured during your installation of the framework. Whenever the CI Remediation occurs, it doesn't need to pass in any parameters since Process-SetupDiag should already have the correct paths hardcoded into the params.

Here's a sample of what the file should look like after you've installed the framework.
![image](https://user-images.githubusercontent.com/20917262/121377411-f0646f00-c907-11eb-9819-8337672bc527.png)

```ps
Function Process-SetupDiag {
    [cmdletbinding()]
    param (
        [string]$LocalLogRoot = "C:\~FeatureUpdateTemp\Logs",
        [string]$CallingScript = "None",
        [string]$TranscriptPath = "C:\Windows\CCM\Logs\FeatureUpdate-Process-SetupDiag.log",
        [string]$SetupDiagPath = $PSScriptRoot,
        [switch]$SkipSetupDiag,
        [switch]$SkipWriteRegKey
    )
        #Set the status to the script name that called it until we process the results.
        $Status = $CallingScript

        #cleanup any existing logs
        Get-ChildItem -Path $TranscriptPath,$LocalLogRoot -ErrorAction SilentlyContinue | Remove-Item -Force -Recurse -ErrorAction SilentlyContinue | Out-Null
```


Additionally, you mention that you are using this for your customers.  Surely, you did some testing before you pushed this out to all of their clients. I use this same code in my production environment and have done lots of testing on it, but can't cover all scenarios.
